FROM docker.io/library/node:22-alpine

WORKDIR /workspace

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY scripts ./scripts

RUN corepack enable && pnpm install --frozen-lockfile
RUN pnpm --filter @niar/database prisma:generate
RUN pnpm --filter @niar/admin-api build

ENV NODE_ENV=production

EXPOSE 3333

CMD ["pnpm", "--filter", "@niar/admin-api", "exec", "tsx", "src/server.ts"]
